---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, ransomware protection' 
summary: 了解勒索软件保护的新增功能。 
---
= 勒索软件保护的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解勒索软件保护的新增功能。



== 2022年6月12日



=== 现在、系统将跟踪ONTAP Storage VM的NAS文件系统审核状态

如果工作环境中启用了文件系统审核的Storage VM少于40%、则会向_Cyber Resilience Map_添加警报。您可以在_harden your ONTAP environment_面板中查看未跟踪SMB和NFS事件并将其记录到审核日志中的确切SVM数。然后、您可以决定是否对这些SVM启用审核。



=== 现在、如果您的卷未启用机载反勒索软件、则会显示警报

先前在_harden your ONTAP Environments_panel中为内部ONTAP 系统报告了此信息、 但现在、当在40%以下的卷中启用了机载反勒索软件功能时、_Cyber Resilience Map_中会报告一条警报、因此您可以在信息板中查看此信息。



=== 现在、可跟踪适用于ONTAP 系统的FSX以启用卷快照

现在、增强ONTAP 环境_面板可提供适用于ONTAP 系统的FSx上卷的Snapshot副本状态。如果不到40%的卷受快照保护、您还会在_Cyber Resilience Map_中收到警报。



== 2022年5月11日



=== 用于跟踪 ONTAP 环境安全性强化情况的新面板。

一个新面板_harden your ONTAP Environments_可 提供ONTAP 系统中某些设置的状态、用于根据跟踪部署的安全性 https://www.netapp.com/pdf.html?item=/media/10674-tr4569.pdf["《适用于 ONTAP 系统的 NetApp 安全加固指南》"^] 和 https://docs.netapp.com/us-en/ontap/anti-ransomware/index.html["ONTAP 防勒索软件功能"^] 主动检测异常活动并发出警告。

您可以查看这些建议，然后确定希望如何解决潜在问题。您可以按照以下步骤更改集群上的设置，将更改推迟到其他时间或忽略此建议。 https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#status-of-ontap-systems-hardening["有关详细信息，请访问此处"]。



=== 新面板可显示如何使用 Cloud Backup 保护不同类别的数据。

此全新的_Backup Status_面板显示了在因勒索软件攻击而需要恢复时、您最重要的数据类别的备份程度如何全面。此数据直观地展示了 Cloud Backup 在环境中备份的特定类别项目数量。 https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#backup-status-of-your-critical-business-data["有关详细信息，请访问此处"]。



== 2022 年 3 月 15 日



=== 用于跟踪业务关键型数据的权限状态的新面板

新的"业务关键型数据权限分析"面板可显示对您的业务至关重要的数据的权限状态。这样，您就可以快速评估业务关键型数据的保护情况。 https://docs.netapp.com/us-en/cloud-manager-ransomware/task-analyze-ransomware-data.html#status-of-permissions-on-your-critical-business-data["有关详细信息，请访问此处"]。



=== 现在， " 打开权限 " 区域包括 OneDrive 和 SharePoint 帐户

现在，勒索软件保护信息板中的 " 打开权限 " 区域包含对 OneDrive 帐户和 SharePoint 帐户中正在扫描的文件的现有权限。



== 2022 年 2 月 9 日



=== 全新的勒索软件保护服务

通过全新的勒索软件保护服务，您可以查看有关网络安全的相关信息，并评估数据对网络攻击的弹性。此外，它还会为您提供一系列警报和修复措施，帮助您提高数据的安全性。

link:concept-ransomware-protection.html["了解有关此新服务的更多信息"]。
